### PR TITLE
Export `observeResize`

### PR DESCRIPTION
**Pull request by lolmaus**
Hi! Thanks for the awesome modifier!

I'm planning a major upgrade of my [ember-element-query](https://github.com/lolmaus/ember-element-query) addon. Here's a [readme](https://github.com/lolmaus/ember-element-query/tree/gen-4#ember-element-query) for a version that does not exist yet.

I would like my addon to offer a modifier that uses `ResizeObserver` on the element and does a lot of stuff, including caching previous results.

I've figured that if I was able to import `observeResize` from your addon, I could call it in my modifier instead of copy-pasting `observerResize` code into my addon.

### CODE REVIEW

**Comment by alexlafroscia** [comment]
Neat! Yeah, that's really cool. I'm happy for you to be able to import the modifier function for you if that's helpful 👍 

I'm going to amend the commit just to follow [the desired format](https://github.com/alexlafroscia/ember-resize-observer-modifier/blob/master/CONTRIBUTING.md#commit-format)

**Comment by alexlafroscia** [comment]
Released in `v1.1.0`

**Comment by lolmaus** [comment]
Thank you so much!

Here's how I use it:
https://github.com/lolmaus/ember-element-query/blob/gen-4/addon/-private/modifier.ts#L239

Works flawlessly. 😎

Here's the readme of my WIP addon version if you're curious: 
https://github.com/lolmaus/ember-element-query/tree/gen-4#ember-element-query

**Comment by alexlafroscia** [comment]
Very cool! I’m glad that worked for you. Always nice to have a chance to share some code rather than duplicate it across packages!

**Pull request merged**
